// examples/typescript5/src/App.vue
<script setup lang="ts">
import { useV } from 'phecda-vue'
import HelloWorld from './components/HelloWorld.vue'
import { HomeModel } from './models/home'
const { name } = useV(HomeModel)
</script>

<template>
  <div>
    {{ name }}
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo">
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo">
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// examples/react/src/App.tsx
import { useState } from "react";
import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import "./App.css";
import { Home } from "./Home";
import { emitter } from "phecda-react";




function App() {
  const [isMount, changeMount] = useState(true);

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <button onClick={()=>emitter.emit('update','watcher')}>event emitter</button>
      <button onClick={() => changeMount(!isMount)}>{isMount?'mounting':'unmounting'}</button>
      {isMount && <Home></Home>}
    </>
  );
}

export default App;
