// examples/vue/src/App.vue
<!-- eslint-disable vue/comma-dangle -->
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router'
import { usePhecda, useR } from 'phecda-vue'
import { UserModel } from '@/models/user'

const User = useR(UserModel)
const { reset } = usePhecda()
</script>

<template>
  <header>
    <RouterLink to="/">
      Home
    </RouterLink>
    <RouterLink to="/about">
      About
    </RouterLink>
    name: <p> {{ User.name }}</p>
    fullName: <p> {{ User.fullName }}</p>

    <img alt="Vue logo" class="logo" src="@/assets/logo.svg" width="125" height="125">

    <div class="wrapper">
      <nav>
        <button @click="reset(UserModel)">
          initlize
        </button>
      </nav>
    </div>
  </header>

  <RouterView />
</template>

// examples/react/src/App.tsx

import "./App.css";
import { Home } from "./views/Home";
import { PhecdaContext, createPhecda, usePhecda } from "phecda-react";

import {
  createBrowserRouter,
  RouterProvider,

  Link,
} from "react-router-dom";
import { UserModel } from "./models/user";
const router = createBrowserRouter([
  {
    path: "/",
    element: <Home></Home>,
  },
  // {
  //   path: "about",
  //   element: <About></About>
  // },
]);

function App() {
  const { reset } = usePhecda();
  return (
    <>
      <PhecdaContext.Provider value={createPhecda()}>
        <button onClick={()=>reset(UserModel)}>initlize</button>
        {/* <Link to="about">About Us</Link> */}

        <RouterProvider router={router}></RouterProvider>
      </PhecdaContext.Provider>
    </>
  );
}

export default App;
